# src/Aston/FrontBundle/Resources/config/routing.yml

aston_front_homepage:
    path:     /
    defaults: { _controller: AstonFrontBundle:Default:index }

aston_front_contact:
    path:     /contact
    defaults: { _controller: AstonFrontBundle:Default:contact }
